#!/bin/sh

diff=$(git diff)
if [[ $diff != "" ]]
then
  echo "\033[31m 你还有文件没有提交，先 commit 你的代码 (·_·) \033[0m"
  files=$(git diff --name-only)
  echo "\n"
  for file in ${files}; do
    echo "   $file"
  done;
  echo "\n"
  exit 1
fi

# yarn add ssh:git@code.aliyun.com:yopoint/yp-pkg-i18n-error.git#develop
yarn build
echo "\n"

echo "\033[32m 构建完成 \033[0m"
echo "\n"

# node .hooks/upload.oss.js
echo "\033[32m 上传完成 \033[0m"
echo "\n"

git commit -am '[auto]: build local'
echo "\n"
echo "\033[32m commit: build local \033[0m"
echo "\n"

git pull --rebase
git push
echo "\n"
echo "\033[32m 部署完成 \033[0m"
echo "\n"

exit 0
